export const roleDefaults = {
  tank: { manaPerAttack: 5, manaRegenPerSecond: 0, castTime: 1, manaLock: 0.5 },
  fighter: { manaPerAttack: 10, manaRegenPerSecond: 0, castTime: 1, manaLock: 0.5 },
  caster: { manaPerAttack: 7, manaRegenPerSecond: 2, castTime: 1, manaLock: 0.5 },
  marksman: { manaPerAttack: 10, manaRegenPerSecond: 0, castTime: 1, manaLock: 0.5 },
  assassin: { manaPerAttack: 10, manaRegenPerSecond: 0, castTime: 1, manaLock: 0.5 },
};

export const simDefaults = {
  canCastAfterAutoProgress: 0.3,
  requiresAttackBetweenCasts: false,
  projectileDelay: 0,
  tickInterval: null,
};

export const targetPresets = {
  standard_frontline: { name: "\u6807\u51c6\u524d\u6392", hp: 1800, armor: 100, mr: 100 },
  squishy: { name: "\u8106\u76ae", hp: 1200, armor: 45, mr: 45 },
  heavy_tank: { name: "\u91cd\u5766", hp: 2800, armor: 160, mr: 160 },
};

export const heroes = [
  {
    id: "ahri",
    name: "\u963f\u72f8",
    cost: 2,
    role: "caster",
    traits: ["Astral", "Invoker"],
    base: {
      hp: [650, 1170, 2106],
      ad: [30, 45, 68],
      as: 0.8,
      armor: 20,
      mr: 20,
      range: 4,
      critChance: 0.25,
      critDamage: 1.4,
      manaStart: 0,
      manaMax: 30,
      apBase: 1,
      damageAmpBase: 1,
    },
    ability: {
      name: "\u7075\u706b",
      type: "magic",
      baseValues: { damage: [130, 195, 310] },
      scalings: { apRatio: 0.85 },
      spellCrit: false,
      description: "Launches fox-fire bolts that deal magic damage.",
    },
  },
  {
    id: "shen",
    name: "\u614e",
    cost: 5,
    role: "tank",
    traits: ["Duskwall", "Bastion"],
    base: {
      hp: [1300, 2340, 4212],
      ad: [50, 75, 113],
      as: 0.95,
      armor: 75,
      mr: 75,
      range: 1,
      critChance: 0.25,
      critDamage: 1.4,
      manaStart: 10,
      manaMax: 70,
      apBase: 1,
      damageAmpBase: 1,
    },
    ability: {
      name: "\u73b0\u5b9e\u6495\u88c2",
      type: "magic",
      baseValues: { damage: [329, 487, 3793], shield: [329, 487, 3793] },
      scalings: { apRatio: 0.55, healthRatio: 0.08 },
      spellCrit: false,
      description: "Leaps into the enemy cluster, deals magic damage, and gains a shield.",
    },
  },
  {
    id: "samira",
    name: "\u838e\u5f25\u62c9",
    cost: 4,
    role: "marksman",
    traits: ["Gunslinger", "Breaker"],
    base: {
      hp: [900, 1620, 2916],
      ad: [72, 108, 162],
      as: 0.85,
      armor: 45,
      mr: 45,
      range: 4,
      critChance: 0.25,
      critDamage: 1.4,
      manaStart: 15,
      manaMax: 70,
      apBase: 1,
      damageAmpBase: 1,
    },
    ability: {
      name: "\u98ce\u683c\u5f39\u5e55",
      type: "physical",
      baseValues: { damage: [220, 330, 520] },
      scalings: { adRatio: 1.8 },
      spellCrit: false,
      description: "Dashes and unloads multiple physical shots into the current target.",
    },
    override: {
      requiresAttackBetweenCasts: true,
    },
  },
  {
    id: "ashe",
    name: "\u827e\u5e0c",
    cost: 3,
    role: "marksman",
    traits: ["Aurora", "Sniper"],
    base: {
      hp: [700, 1260, 2268],
      ad: [56, 84, 126],
      as: 0.78,
      armor: 30,
      mr: 30,
      range: 4,
      critChance: 0.25,
      critDamage: 1.4,
      manaStart: 10,
      manaMax: 60,
      apBase: 1,
      damageAmpBase: 1,
    },
    ability: {
      name: "\u51b0\u971c\u9f50\u5c04",
      type: "physical",
      baseValues: { damage: [145, 218, 340] },
      scalings: { adRatio: 1.25 },
      spellCrit: false,
      description: "Empowers follow-up attacks to deal bonus physical damage.",
    },
  },
  {
    id: "vex",
    name: "\u8587\u53e4\u4e1d",
    cost: 3,
    role: "caster",
    traits: ["Shade", "Sorcerer"],
    base: {
      hp: [720, 1296, 2333],
      ad: [40, 60, 90],
      as: 0.75,
      armor: 30,
      mr: 30,
      range: 4,
      critChance: 0.25,
      critDamage: 1.4,
      manaStart: 0,
      manaMax: 40,
      apBase: 1,
      damageAmpBase: 1,
    },
    ability: {
      name: "\u9634\u90c1\u7206\u88c2",
      type: "magic",
      baseValues: { damage: [190, 285, 450] },
      scalings: { apRatio: 0.95 },
      spellCrit: false,
      description: "Detonates gloom energy in a dense area for magic damage.",
    },
  },
  {
    id: "seraphine",
    name: "\u8428\u52d2\u82ac\u59ae",
    cost: 2,
    role: "caster",
    traits: ["Resonance", "Astral"],
    base: {
      hp: [620, 1116, 2009],
      ad: [25, 38, 56],
      as: 0.75,
      armor: 20,
      mr: 20,
      range: 4,
      critChance: 0.25,
      critDamage: 1.4,
      manaStart: 0,
      manaMax: 30,
      apBase: 1,
      damageAmpBase: 1,
    },
    ability: {
      name: "\u56de\u54cd\u8282\u62cd",
      type: "magic",
      baseValues: { damage: [120, 180, 280] },
      scalings: { apRatio: 0.8 },
      spellCrit: false,
      description: "Releases a wave that deals magic damage and boosts later casts.",
    },
  },
  {
    id: "darius",
    name: "\u5fb7\u83b1\u5384\u65af",
    cost: 2,
    role: "fighter",
    traits: ["Ironblood", "Bruiser"],
    base: {
      hp: [780, 1404, 2527],
      ad: [60, 90, 135],
      as: 0.75,
      armor: 45,
      mr: 45,
      range: 1,
      critChance: 0.25,
      critDamage: 1.4,
      manaStart: 20,
      manaMax: 70,
      apBase: 1,
      damageAmpBase: 1,
    },
    ability: {
      name: "\u65ad\u5934\u53f0",
      type: "physical",
      baseValues: { damage: [180, 270, 430] },
      scalings: { adRatio: 1.5 },
      spellCrit: false,
      description: "Swings through the target and deals high physical damage.",
    },
  },
  {
    id: "jhin",
    name: "\u70ec",
    cost: 4,
    role: "marksman",
    traits: ["Reaper", "Sniper"],
    base: {
      hp: [820, 1476, 2656],
      ad: [68, 102, 153],
      as: 0.74,
      armor: 35,
      mr: 35,
      range: 4,
      critChance: 0.25,
      critDamage: 1.4,
      manaStart: 0,
      manaMax: 55,
      apBase: 1,
      damageAmpBase: 1,
    },
    ability: {
      name: "\u5b8c\u7f8e\u8c22\u5e55",
      type: "physical",
      baseValues: { damage: [210, 315, 500] },
      scalings: { adRatio: 1.65 },
      spellCrit: false,
      description: "Loads an empowered shot that deals extra physical damage.",
    },
  },
  {
    id: "illaoi",
    name: "\u4fc4\u6d1b\u4f0a",
    cost: 3,
    role: "tank",
    traits: ["Abyss", "Bastion"],
    base: {
      hp: [980, 1764, 3175],
      ad: [55, 83, 124],
      as: 0.7,
      armor: 55,
      mr: 55,
      range: 1,
      critChance: 0.25,
      critDamage: 1.4,
      manaStart: 30,
      manaMax: 80,
      apBase: 1,
      damageAmpBase: 1,
    },
    ability: {
      name: "\u89e6\u624b\u98ce\u66b4",
      type: "magic",
      baseValues: { damage: [150, 225, 350], shield: [250, 375, 600] },
      scalings: { apRatio: 0.7, healthRatio: 0.06 },
      spellCrit: false,
      description: "Slams the ground for magic damage and gains a shield.",
    },
  },
  {
    id: "ziggs",
    name: "\u5409\u683c\u65af",
    cost: 1,
    role: "caster",
    traits: ["Boom", "Mechanic"],
    base: {
      hp: [540, 972, 1749],
      ad: [20, 30, 45],
      as: 0.75,
      armor: 15,
      mr: 15,
      range: 4,
      critChance: 0.25,
      critDamage: 1.4,
      manaStart: 0,
      manaMax: 30,
      apBase: 1,
      damageAmpBase: 1,
    },
    ability: {
      name: "\u5f39\u8df3\u70b8\u5f39",
      type: "magic",
      baseValues: { damage: [100, 150, 235] },
      scalings: { apRatio: 0.78 },
      spellCrit: false,
      description: "Throws a bomb that explodes for area magic damage.",
    },
  },
];

const makeExtra = (id, name, category, order, config) => ({
  id,
  name,
  category,
  order,
  flatStats: {},
  hooks: {},
  notes: "",
  ...config,
});

export const categories = [
  { id: "craftable", label: "\u53ef\u5408\u6210" },
  { id: "artifact", label: "\u5965\u672f\u88c5\u5907" },
  { id: "radiant", label: "\u5149\u660e\u88c5\u5907" },
  { id: "emblem", label: "\u7eb9\u7ae0" },
  { id: "trait", label: "\u7f81\u7eca" },
  { id: "buff", label: "\u5f3a\u5316\u7b26\u6587/Buff" },
];

export const extras = [
  makeExtra("rabadon", "Rabadon's Deathcap", "craftable", 43, { flatStats: { apFlat: 0.7 } }),
  makeExtra("archangel", "Archangel's Staff", "craftable", 5, {
    flatStats: { apFlat: 0.25 },
    hooks: { perSecondAp: 0.025, maxPerSecondAp: 0.5 },
  }),
  makeExtra("jeweled-gauntlet", "Jeweled Gauntlet", "craftable", 30, {
    flatStats: { apFlat: 0.35, critChance: 0.25 },
    hooks: { enableSpellCrit: true },
  }),
  makeExtra("giant-slayer", "Giant Slayer", "craftable", 18, {
    flatStats: { adFlat: 12, apFlat: 0.15 },
    hooks: { conditionalDamageAmp: { targetHpAtLeast: 1600, amp: 0.22 } },
  }),
  makeExtra("void-staff", "Void Staff", "craftable", 76, {
    flatStats: { apFlat: 0.15, manaRegen: 3 },
    hooks: { magicPenFlat: 35 },
  }),
  makeExtra("shojin", "Spear of Shojin", "craftable", 67, {
    flatStats: { adFlat: 15, manaRegen: 1 },
    hooks: { bonusManaOnAttack: 5 },
  }),
  makeExtra("guinsoo", "Guinsoo's Rageblade", "craftable", 22, {
    flatStats: { asFlat: 0.12 },
    hooks: { attackSpeedPerAttack: 0.035, attackSpeedCapBonus: 1.15 },
  }),
  makeExtra("giant-slayer-lite", "Giant Slayer (no Giant)", "craftable", 19, {
    flatStats: { adFlat: 12, apFlat: 0.15 },
  }),
  makeExtra("tacticians-crown", "Tactician's Crown", "craftable", 71, {
    flatStats: { apFlat: 0.25, asFlat: 0.15, damageAmp: 0.08 },
  }),
  makeExtra("hand-of-justice", "Hand of Justice", "craftable", 25, {
    flatStats: { critChance: 0.2, apFlat: 0.15, adFlat: 10 },
    hooks: { conditionalDamageAmp: { targetHpAtLeast: 0, amp: 0.12 } },
  }),
  makeExtra("deaths-defiance", "Death's Defiance", "artifact", 3, {
    flatStats: { adFlat: 24, asFlat: 0.18 },
    hooks: { onHitTrueBonus: 12 },
  }),
  makeExtra("lich-bane", "Lich Bane", "artifact", 7, {
    flatStats: { apFlat: 0.35 },
    hooks: { afterCastBonusMagic: 80 },
  }),
  makeExtra("snipers-focus", "Sniper's Focus", "artifact", 12, {
    flatStats: { adFlat: 18, critChance: 0.2, damageAmp: 0.1 },
  }),
  makeExtra("eternal-whisper", "Eternal Whisper", "artifact", 16, {
    flatStats: { apFlat: 0.3, manaRegen: 2 },
    hooks: { magicPenFlat: 20, perSecondAp: 0.015, maxPerSecondAp: 0.3 },
  }),
  makeExtra("rabadon-radiant", "Radiant Deathcap", "radiant", 9, {
    flatStats: { apFlat: 1.1, damageAmp: 0.08 },
  }),
  makeExtra("shojin-radiant", "Radiant Shojin", "radiant", 14, {
    flatStats: { adFlat: 20, manaRegen: 3 },
    hooks: { bonusManaOnAttack: 8 },
  }),
  makeExtra("guinsoo-radiant", "Radiant Rageblade", "radiant", 18, {
    flatStats: { asFlat: 0.22, damageAmp: 0.05 },
    hooks: { attackSpeedPerAttack: 0.05, attackSpeedCapBonus: 1.4 },
  }),
  makeExtra("jg-radiant", "Radiant Jeweled Gauntlet", "radiant", 24, {
    flatStats: { apFlat: 0.5, critChance: 0.35 },
    hooks: { enableSpellCrit: true, bonusSpellCritDamage: 0.15 },
  }),
  makeExtra("bastion-emblem", "Bastion Emblem", "emblem", 2, { flatStats: { armorFlat: 25, mrFlat: 25 } }),
  makeExtra("sorcerer-emblem", "Sorcerer Emblem", "emblem", 8, { flatStats: { apFlat: 0.3 } }),
  makeExtra("marksman-emblem", "Marksman Emblem", "emblem", 11, {
    flatStats: { adFlat: 12, critChance: 0.15 },
  }),
  makeExtra("fighter-emblem", "Fighter Emblem", "emblem", 15, { flatStats: { hpFlat: 180, adFlat: 10 } }),
  makeExtra("chrono-emblem", "Chrono Emblem", "emblem", 20, { flatStats: { asFlat: 0.15, manaRegen: 1 } }),
  makeExtra("trait-bastion-4", "Bastion 4", "trait", 4, { flatStats: { armorFlat: 35, mrFlat: 35 }, traitKey: "bastion" }),
  makeExtra("trait-sorcerer-4", "Sorcerer 4", "trait", 6, { flatStats: { apFlat: 0.45 }, traitKey: "sorcerer" }),
  makeExtra("trait-sniper-2", "Sniper 2", "trait", 10, { flatStats: { damageAmp: 0.12 }, traitKey: "sniper" }),
  makeExtra("trait-vanguard-4", "Vanguard 4", "trait", 13, { flatStats: { hpFlat: 260, armorFlat: 20 }, traitKey: "vanguard" }),
  makeExtra("trait-arcane-3", "Arcane 3", "trait", 21, { flatStats: { manaRegen: 2, apFlat: 0.18 }, traitKey: "arcane" }),
  makeExtra("buff-blue", "Blue Buff", "buff", 1, { flatStats: { manaRegen: 3, apFlat: 0.15 } }),
  makeExtra("buff-red", "Red Buff", "buff", 5, { flatStats: { damageAmp: 0.14, adFlat: 8 } }),
  makeExtra("buff-gold", "Gold Buff", "buff", 7, { flatStats: { apFlat: 0.2, hpFlat: 180, manaRegen: 1 } }),
  makeExtra("buff-purple", "Prismatic Buff", "buff", 12, {
    flatStats: { critChance: 0.2, critDamage: 0.2, damageAmp: 0.05 },
  }),
  makeExtra("buff-green", "Green Buff", "buff", 14, { flatStats: { hpFlat: 320, apFlat: 0.1 } }),
];
